### ISSUE TITLE
SSID selection goes to unencypted

### ISSUE THREAD

**Issue by hblanken** [davesteele/comitup#1]
Hi David, I am testing your comitup image.

When I logon to 10.42.0.1 I enter my SSID it takes me to the unencrypted page and I cannot enter a password. I manually removed the 'un' and it worked fine, but still a tiny bug to remove.

http://10.42.0.1/confirm?ssid=XXX&encrypted=unencrypted

**Comment by davesteele** [comment]
Does that edit fix it?

**Comment by tehDrew** [comment]
It did not fix it for me; glad I happened to glance at the url and see "unencrypted" and manually changed it.  Using WPA2 PSK.

**Comment by davesteele** [comment]
As it happens, I've run across this as well, with a new Wifi Router 

To check if my fix works for you (183637d0), check if the command 'sudo iw dev wlan0 scan' shows an 'RSN:' section for your AP's SSID.

**Comment by tehDrew** [comment]
it does show an RSN section under my router

**Comment by davesteele** [comment]
Then it should be fixed in the next release.

**Comment by tehDrew** [comment]
Thanks, davesteele!!  This is a very handy image you've made for those of us with wireless Pi's.  Your work is much appreciated :1st_place_medal:

**Comment by davesteele** [comment]
fixed
