### ISSUE TITLE
how to change the domain name

### ISSUE THREAD

**Issue by santhoshnp** [davesteele/comitup#117]
Hi team,

I have one doubt in domain name .how to change 10.41.0.1 into different name for example 10.41.0.1 to comitup. It is possible when Captive portal take place while connecting the WiFi?

**Comment by davesteele** [comment]
See the [ZeroConfBrowser](https://github.com/davesteele/comitup/wiki/ZeroconfBrowser) wiki page. Also, the "ap_name" parameter in [comitup.conf](https://davesteele.github.io/comitup/man/comitup-conf.5.html).
