### ISSUE TITLE
DNS issues on Raspberry Pi

### ISSUE THREAD

**Issue by davesteele** [davesteele/comitup#120]
A problem has been introduced recently, with contention between systemd-resolved and Comitup causing DNS resolution to fail.

A fix for this has been [added to the wiki](https://github.com/davesteele/comitup/wiki/Installing-Comitup/_compare/c36ed739022b0e3a3b53cec360408aa2a2c0b243...9694ed6c77e2e06c091736e041af46e04d894f9a). The 2020-07-27 iso image has a fix, with the systemd-resolved service masked. Comitup v1.11-1 also [detects the condition and logs](https://github.com/davesteele/comitup/commit/a83c7fda4268dc988aad677ba9576cf0e743cb3c).

**Comment by muelli** [comment]
And here's the reference to a potential fix: https://github.com/davesteele/comitup/issues/51 :)
