### ISSUE TITLE
wifi connection problem

### ISSUE THREAD

**Issue by asadasivam** [davesteele/comitup#121]
Hi team,

I have two routers. So First I have connected in one router by using comitup os(raspberry pi)it is connected successfully and I power off the router and  tried to connect with another router it is not connecting it shows authentication error I don't why can you please
explain to me about this I am so enthusiastic to learn about this

**Comment by davesteele** [comment]
I don't think the fact that you have two routers involved has anything to do with the problem (unless they have the same ssid).

Does NetworkManager have anything to say about the failure? (sudo grep NetworkManager /var/log/user.log).

Note that the configuration for the connection is stored in /etc/NetworkManager/system-connections. You can work on details from there.

Also note that you can invoke the connections from NetworkManager itself:

sudo systemctl stop comitup
sudo nmcli con up &lt;ssid&gt;

**Comment by asadasivam** [comment]
Thank you so much for the response, but it showing

**Comment by asadasivam** [comment]
It is showing like this 
![InkedIMG-20200804-WA0009_LI](https://user-images.githubusercontent.com/48304665/89272460-d01ab280-d65b-11ea-87eb-7e75d3b14ae5.jpg)

**Comment by asadasivam** [comment]
can you please explain about this

**Comment by davesteele** [comment]
Not really. The connection shows as open, meaning no password is needed. Maybe you're using a USB Wifi for the hotspot which is not well supported by Raspbian.

Comitup implements a "captive portal", using dnsmasq. Perhaps logs for that utility may give some insight.

**Comment by asadasivam** [comment]
No, I am not using USB wifi for the hotspot, so what will be the reason

**Comment by asadasivam** [comment]
it says that couldn't connect to the network why?

**Comment by davesteele** [comment]
i encountered this problem. Resolved with https://github.com/davesteele/comitup/commit/9c044dcd9d436876cdfc0f9ce0948520281901cc, released with v1.15, and the latest image.
