### ISSUE TITLE
Regarding comitup ssid

### ISSUE THREAD

**Issue by santhoshpremnp** [davesteele/comitup#130]
Hi, davesteele,

First of all, it is an amazing project

1) first I downloaded the 2020-07-27-Comitup.img and inserted the sd card into raspberry pi after burning the os

2) Next I waiting for the comitup ssid in the network settings 

3) It takes around 1 minute. ok after that I have connected to my desired wifi.it works fine all ok

4) But when I tried to change the different wifi network at that time comitup SSID is displaying only 3 minutes after that it is hidden from the network settings I am astonished about this but when I tried in 2019-09-30-Comitup.img it is discovering always why? please help me regarding this I am so enthusiastic about this

**Comment by davesteele** [comment]
NetworkManager does not do a good job of maintaining the list of available access points, when the only interface it has to work with is running an active hotspot.

Comitup has a number of strategies to work with this. If there is another Wifi interface available, it will lean on that that one to get this list. The web interface offers a way to enter in the SSID manually, if you know what it is.

It has been a balancing act between getting a good AP list, and avoiding dropping connected hotspot users. 

Add a second USB Wifi interface, if you can. The list is much better then.
