### ISSUE TITLE
Change address of captive portal

### ISSUE THREAD

**Issue by Golgomaph** [davesteele/comitup#137]
Hey davesteele,

i dont know how captive portal works exactly.. can i change the address it is automatically connecting to (f.e. on android)? I am running a node-red and i wish to manage the wifi-credential thing from there instead of your html-page. 

Instead of 
10.41.0.1

it would be enough to make it connecting to
10.41.0.1:1880/ui/

Is it possible?

**Comment by davesteele** [comment]
You want to change the port?

Yes. grep the source for 10.41.0, and adjust (also see #61).

But, there is a reason captive portals are on port 80 - One of the several captive portal strategies in use depends on hijacking an http request with the wifi config page, which means owning the root page on port 80 (another is driven by the _dhcp_options_ in *dns-hotspot.conf*.

Make sure you understand the _web_service_ parameter in the config file.
