### ISSUE TITLE
Dependencies list

### ISSUE THREAD

**Issue by bkchr** [davesteele/comitup#143]
Hey, 
I already search, but couldn't find a clear dependency list? I would be happy with the files you use to setup the deb package.

I probably want to port this to Nixos and having a dependency list (programs that needs to be installed etc) would make it much easier for me.

Ty :)

**Comment by davesteele** [comment]
Dependencies are defined in setup.py, and in debian/control in the debian branch.

**Comment by bkchr** [comment]
Ahh there is a `debian` branch. Perfect! That was what I searched for :)
