### ISSUE TITLE
Unable to connect to a WiFi with no password

### ISSUE THREAD

**Issue by BolnayaTPrincessa** [davesteele/comitup#144]
The browser keeps requesting a password when I click at the "connect" button at the WiFi select interface, thus unable to connect to a WiFi with no password. Quite similar to #42, but no solution is provided.

**Comment by davesteele** [comment]
Let's start with [CONTRIBUTING](https://github.com/davesteele/comitup/blob/master/CONTRIBUTING.md).

**Comment by BolnayaTPrincessa** [comment]
I've used the same Pi to connect to another WiFi with a password successfully, with no errors occurred. When I attempt to connect to a WiFi having no password, the hotspot selection webpage displays properly, the only problem is that it keeps preventing me to connect to the no-password WiFi.

**Comment by davesteele** [comment]
Can't reproduce. I just used Comitup to connect to another Comitup Pi in hotspot mode, with no password.

Are you running current code?
