### ISSUE TITLE
how to disconnect from a Wifi

### ISSUE THREAD

**Issue by dheim-pi** [davesteele/comitup#151]
Hello, is there any way to reset or disconnect from a wifi connection through comitup.
Or to forget wifi connections that I entered

**Comment by davesteele** [comment]
Delete the connection using comitup-cli or D-Bus. See the man pages for comitup-cli and comitup.

**Comment by dheim-pi** [comment]
Many Thanks for the quick replay.  I was not aware about comitup-cli.

**Comment by revantjhalani** [comment]
@davesteele  I tried using the ciu_client.ciu_delete(connection) method by importing the library and loading the connection variable through state. 
But that basically disconnects from wifi without the wifi coming back up again.
My preferred method of disconnection via a python script was to just run a subprocess and pass d and then q to comitup-cli command but that works once or twice and then just doesn't.
Is there a better way to disconnect? Or am I doing something wrong with the ciu_delete method?

**Comment by davesteele** [comment]
Ciu_client and d do the same thing. If you just disconnect, comitup will just reconnect again.
