### ISSUE TITLE
Nothing happend when i run comitup-cli

### ISSUE THREAD

**Issue by 9acca9** [davesteele/comitup#152]
Hi.
First time i try to use your work.
Im connect to the raspberry pi zero w throug  ssh. I install comit-up. And try to run comitup-cli but nothing happend.
What could i try?
Thanks.

In the log i have this:
```

2021-03-26 20:10:47,159 - comitup - INFO - Starting comitup
2021-03-26 20:10:59,002 - comitup - INFO - Starting comitup
2021-03-26 20:11:09,674 - comitup - INFO - Starting comitup
2021-03-26 20:11:20,980 - comitup - INFO - Starting comitup
2021-03-26 20:11:31,846 - comitup - INFO - Starting comitup
2021-03-26 20:11:42,214 - comitup - INFO - Starting comitup
2021-03-26 20:11:53,057 - comitup - INFO - Starting comitup
2021-03-26 20:12:07,638 - comitup - INFO - Starting comitup
2021-03-26 20:12:19,010 - comitup - INFO - Starting comitup
2021-03-26 20:12:30,728 - comitup - INFO - Starting comitup
2021-03-26 20:12:45,967 - comitup - INFO - Starting comitup
2021-03-26 20:12:57,872 - comitup - INFO - Starting comitup
2021-03-26 20:13:09,228 - comitup - INFO - Starting comitup
2021-03-26 20:13:25,987 - comitup - INFO - Starting comitup
```
And when trying: 

```
 sudo comitup -c
Traceback (most recent call last):
  File "/usr/sbin/comitup", line 11, in <module>
    load_entry_point('comitup==1.17', 'console_scripts', 'comitup-cmd')()
  File "/usr/share/comitup/comitup/comitup.py", line 105, in main
    if wificheck.run_checks():
  File "/usr/share/comitup/comitup/wificheck.py", line 117, in run_checks
    testresult = testspec.testfn()
  File "/usr/share/comitup/comitup/wificheck.py", line 68, in device_nm_managed
    devsinfo = subprocess.check_output(cmd.split(), re.MULTILINE).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 589: invalid continuation byte
```

**Comment by davesteele** [comment]
Comitup-cli will have to be restarted whenever comitup is restarted. It won't help here.

The line in question runs the command "nmcli device show", as root. Can you post the output of that command?

**Comment by 9acca9** [comment]
@davesteele 
HI.
Thanks.

I have this from the command. It seems related to my language (spanish).

```
GENERAL.DEVICE:                         wlan0
GENERAL.TYPE:                           wifi
GENERAL.HWADDR:                         F2:91:0B:50:3D:E7
GENERAL.MTU:                            1500
GENERAL.STATE:                          20 (no disponible)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --

GENERAL.DEVICE:                         lo
GENERAL.TYPE:                           loopback
GENERAL.HWADDR:                         00:00:00:00:00:00
GENERAL.MTU:                            65536
GENERAL.STATE:                          10 (sin gesti<F3>n)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.ADDRESS[1]:                         127.0.0.1/8
IP4.GATEWAY:                            --
IP6.ADDRESS[1]:                         ::1/128
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ::1/128, nh = ::, mt = 256

```

In "general state" probably says "sin gestión" with the ó. How i can fix this?
Thanks for your time.

**Comment by davesteele** [comment]
The special character is the problem, but it shouldn't be. The code should handle it.
This is just hardware checking code. I'm going to just tolerate the error (a458fbe). If you would like to try this out, edit the file at /usr/share/comitup/comitup/wificheck.py on your system.

**Comment by 9acca9** [comment]
> The special character is the problem, but it shouldn't be. The code should handle it.
> This is just hardware checking code. I'm going to just tolerate the error ([a458fbe](https://github.com/davesteele/comitup/commit/a458fbe754489138aa4d0821d3ec174f6afe870a)). If you would like to try this out, edit the file at /usr/share/comitup/comitup/wificheck.py on your system.

HI.Thanks. But, how i can edit the file. I mean what i have to write/comment out??

**Comment by 9acca9** [comment]
mmm, i just see this https://github.com/davesteele/comitup/wiki/Installing-Comitup
now is working!
Beatiful! Very useful!

**Comment by davesteele** [comment]
If you want to add to the comitup web interface (available only in hotspot mode), it's one of the files in "templates".

**Comment by davesteele** [comment]
> HI.Thanks. But, how i can edit the file. I mean what i have to write/comment out??

For anyone else wanting to make this change, just make the first line of wificheck.py device_nm_managed() "return None", with the text indented four spaces.
