### ISSUE TITLE
dnsmasq fails to use port 53

### ISSUE THREAD

**Issue by mastin-zgz** [davesteele/comitup#163]
Good morning!

Randomly, it stops me assigning ip in access point mode.
`dnsmasq: failed to create listening socket for port 53: Address already in use`
I have deactivated and prayed the systemd.resolved.
I have applied the "systemctl mask dnsmasq.service"
The error continues.
If I look at who uses port 53, I get this.

`udp        0      0 127.0.1.1:53            0.0.0.0:*                           0          22265       3056/dnsmasq
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           110        7432        486/avahi-daemon: r
udp6       0      0 :::5353                 :::*                                110        7433        486/avahi-daemon: r`

Is there any other option that may apply?

Thanks!

**Comment by mastin-zgz** [comment]
As an added information, I have a cable connected to eth0 that provides internet to the machine. I don't know if that could be the cause.

**Comment by davesteele** [comment]
"systemctl status" can tell you who launched the dnsmasq that is hogging the port.

eth0 is not a problem.

**Comment by mastin-zgz** [comment]
Reinstaling the S.O solved the problem.

Thanks!

**Comment by Ataraxiall** [comment]
Its happening again, and is the networkManager

![image](https://user-images.githubusercontent.com/67580921/115255421-89f47900-a12e-11eb-89eb-5cc0cb672d0c.png)

i edit the  /etc/NetworkManager/NetworkManager.conf

and change

`[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq

[ifupdown]
managed=false`

by
`[main]
plugins=ifupdown,keyfile,ofono
dns=8.8.8.8

[ifupdown]
managed=false`

It works but i dont know if is bad change this dns option in NetworkManager.conf...

**Comment by davesteele** [comment]
The _NetworkManager.conf_ file in the Comitup image:

    [main]
    plugins=ifupdown,keyfile
    
    [ifupdown]
    managed=false

**Comment by davesteele** [comment]
I've added this to the "installing' wiki page.
