### ISSUE TITLE
Bug in "config.py" prevents software to start

### ISSUE THREAD

**Issue by DarkCompiled** [davesteele/comitup#166]
The file "config.py", line 129, has the following content:

`data['sn']: _getserial()`

Unfortunately, that is invalid. After upgrading the package and during the byte-code compilation, the package start fails. It does not start, and it immediately disconnects from WiFi.

This was terrible because I'm using it in a Raspberry Pi Zero W, which does not have an Ethernet port, therefore, I completely lost access to the device. 

Please fix this. Thank you.

**Comment by davesteele** [comment]
You are running Jessie or Stretch. See #160.

**Comment by davesteele** [comment]
see #167
