### ISSUE TITLE
"Web Service" questions...

### ISSUE THREAD

**Issue by d8ahazard** [davesteele/comitup#183]
So, here's a good one for you...

The app I'm using in conjunction with Comitup also runs a web service, and so needs to be started and stopped by comitup.

However, my app also has an optional "auto-update" feature that is intended to stop the application service, run a git pull, rebuild the app, and then restart the service.

If I'm using comitup to manage the starting and stopping of this sub-service, is there a way to directly control it via comitup, or should I be starting and stopping comitup instead?

Secondly - is there any way to only run the wifi daemon when NO network connection is detected? I think you are touching on this in #168...but maybe there's something else I'm missing.

**Comment by davesteele** [comment]
There is no way to have Comitup run this process for you. It may be OK to just let your process run. If CONNECTED, Comitup doesn't care, and otherwise the process is going to fail anyway.

Yes, that is #168.
