### ISSUE TITLE
Comitup-<ssss> option?

### ISSUE THREAD

**Issue by Ataraxiall** [davesteele/comitup#192]
Hi!

In previus versions was an option to put the sn in the name of the wifi.

is still posible?
Thanks!

**Comment by Ataraxiall** [comment]
Thanks for you response, i try to enable, but i cant...

what was the last version with this option?

Thaks!

**Comment by davesteele** [comment]
It was reverted by 8ab5545.

Any new changes need to pass devtest.py.
