### ISSUE TITLE
Include apt repository all or arm64 architecture support

### ISSUE THREAD

**Issue by gman77** [davesteele/comitup#197]
Hi,

The older apt repository comitup artifact (w/Ubuntu 20.04) was set to use "all" architecture.(1.10)

However I would like to use the latest release as recommended in the 
https://github.com/davesteele/comitup/wiki/Installing-Comitup

Would it be possible to specify "all" for the latest deb releases in the repo? or to include an arm64 artifact?

**Comment by davesteele** [comment]
I'm confused - which package/version are you saying is not "all".

**Comment by gman77** [comment]
Hi, 
the latest 1.31.deb when trying to install on ubuntu 64bit (raspberry pi) says arch not supported.

**Comment by davesteele** [comment]
I've not tried Ubuntu, but all of the packages in the Comitup repository are "all".

**Comment by gman77** [comment]
My bad I had missed a dependency.
