### ISSUE TITLE
Apache2 and Comitup

### ISSUE THREAD

**Issue by alf4all** [davesteele/comitup#201]
Situation: On a Raspberry Pi 3B with OS 32-bit I have installed apache2 before installing comitup. Now I can access the apache2 default page via WiFi but how can I make a setup to an existing AP? Is it by a webpage or by SSH? did I miss something?

Update: With comitup-web I get the Apache default page en with SSH comitup-cli i can configure comitup nice. Is there an URL to get the web page?

**Comment by alf4all** [comment]
So, reading "Bootstrap Wifi using Wifi" ther must be a comitup-web somewhere...

**Comment by davesteele** [comment]
Comitup and Apache both want/need ownership of port 80 - they can't both run at the same time. See [this example](https://davesteele.github.io/raspberrypi/2021/04/29/comitup-and-pihole/) on how to get such services to coexist. This gives ownership of the port to Comitup when the upstream Wifi connection can't be made.

There are some other potential [complications](https://github.com/davesteele/comitup/wiki/Installing-Comitup) involved with installing Comitup as a package. You may want to start with the [Comitup image](https://davesteele.github.io/comitup/). It is just Raspberry Pi OS with Comitup installed.

**Comment by alf4all** [comment]
Hai Dave, I am now working on the Pi-hole-Comitup example adapted for Apache2. I have not seen the GUI of Comitup yet, but is there an option to choose for a non-connected start of the application? Or do I have to solve that situation in comitup-callback? Thanks for this fantastic application and good service. Regards...

**Comment by alf4all** [comment]
Small remark: Advanced options of Raspberry Pi Imager (Set hostname) do not override the default comitup-NNN of Comitup.

**Comment by davesteele** [comment]
Start with Apache2 disabled, then you should see the GUI (if upstream is not connected at startup). Then configure the callback to start Apache2 when needed.

Comitup will determine the state to start in automatically. If upstream is already connected, the GUI will never come up (single adapter mode).
