### ISSUE TITLE
Comitup 1.36-1 unable to get to website

### ISSUE THREAD

**Issue by Geektoolkit** [davesteele/comitup#204]
I was hitting issues with 1.34, realized that going to 1.36-1 would likely be better, figured out how to turn on the verbose logging, and got back into the state where I can't get the webUI up. I've installed the pyton fix that you mentioned from 1.34 when I hit this, so I believe I either have a new issue, or I'm doing something wrong.   But this time I have logs :)  I have downloaded the debian package for the python patch and installed it...unless there is some way that could get uninstalled I am thinking I'm hitting a new issue.

The behavior I'm seeing is the IP address shows up in ifconfig of 41.10.0.1, and my iphone xs can connect to it ok, but I can't get the webpage to come up. I had it working, but then edited the config file to name it 'frame' instead of comitup-xxxx  for the project I'm working on.  I also turned on verbose logging, the rest is default.  

Attatched are the comitup log, the comitup-web log and the syslog. The syslog is where I see tracebacks that make me think that's where the issues are being shown, but including all three for verbosity.  

I'm hoping I caught a good bug and the logs are helpful. I've attatched them. The syslog I thought was most interesting. It has in it:

I've spent 3 days on and off hitting this, and every time I reinstall (raspbian OS, buster, using the instructions provided) I think I got past it as it'll work once or twice. but eventually I end up in this state where I can't get the webUI to show up.

[syslog.txt](https://github.com/davesteele/comitup/files/8649782/syslog.txt)
[comituplog.txt](https://github.com/davesteele/comitup/files/8649786/comituplog.txt)
[comitup-web.txt](https://github.com/davesteele/comitup/files/8649789/comitup-web.txt)

**Comment by Geektoolkit** [comment]
I tried installing the debian package for the python fix just to make absolutely sure it wasn't that (or that that didn't fix it) and confirmed I'm still stuck. Not sure what else to try.

**Comment by davesteele** [comment]
From syslog.txt, "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 69232: ordinal not in range(128)".

I sounds like you have a visible Access Point who's name includes a non-ascii (unicode?) character, and comitup is crashing on that - a situation it clearly should be able to handle.

I'll take a look at it. The culprit is iwscan.py line 24, where the "ascii" encoding should probably be "utf-8". There may be ramifications to the change - I don't know if the Zeroconf service pub works with non-ascii strings.

An ugly hack would be to replace line 25 as follows:
from

    except subprocess.CalledProcessError:

to

    except (subprocess.CalledProcessError, UnicodeDecodeError):

This would make the offending AP disappear from the list.

Can you tell me the offending AP name?

The output to "sudo iw dev wlan0 scan" could help as well.

This issue has some [history](https://github.com/davesteele/comitup/issues/193).

**Comment by davesteele** [comment]
The commit above may solve your problem, but there is still an issue with ip address discovery if you connect to the AP with unicode. I'm leaving this open to track that issue.

**Comment by Geektoolkit** [comment]
[out (1).txt](https://github.com/davesteele/comitup/files/8667056/out.1.txt)

Thankyou!  I'll give that a shot, before I did I wanted to get this to you....running that command produced the attatched output txt file. I suspect this may be a problem:

last seen: 0 ms ago
	SSID: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
	Supported rates: 6.0* 9.0 12.0* 18.0 24.0* 36.0 48.0 54.0 
	TIM: DTIM Count 1 DTIM Period 3 Bitmap Control 0x0 Bitmap[0] 0x0
	
	That SSID Doesn't show up on my iphone, so not sure if it's hidden and named wacky or what.  The NCC1701D in the list never shows up on anything else...if that command finds hidden SSID's that's handy  :)
	
	I'll give that build a try and report back. Thankyou for the fast turnaround!

**Comment by Geektoolkit** [comment]
Initial testing is looking good! I'll keep testing it and see how things go, but right off I was able to connect where I wasn't before.

**Comment by davesteele** [comment]
Ok. Closing this. The next problem is independent.
