### ISSUE TITLE
Can't change SSID of AP...

### ISSUE THREAD

**Issue by GrandChriss** [davesteele/comitup#207]
Hello,

My problem is, that I changing app_name in /etc/comitup.conf file, but AP name still is comitup-xx. I tried to reinstall Comitup, but nothing works, maybe this functions is not available any more?

**Comment by davesteele** [comment]
Be sure that the variable you are changing in /etc/comitup.conf is "ap_name" - that's "ap" an in "access point".

**Comment by ass805** [comment]
<img width="960" alt="commitup-conf" src="https://user-images.githubusercontent.com/10962202/168053124-f9b37968-fe1a-491c-b123-02533567711b.png">

That's how looking my config file. I was trying to change "ap_name: Nothing" and it still showing as "comitup-24" after reboot.
Maybe there is more I can show you to detect this problem?
Also, I have a question about HTML page editting, is it possible when comitup already installed in Pi? Where I can find Web interface files?

I'm using: Raspberry Pi Zero W + Debian Buster Raspbian OS Desktop

**Comment by GrandChriss** [comment]
I solved that problem. Changed ap_name in /usr/share/comitup/comitup/comitup.py file. 

I have another question, where I can find command when after reboot checking Wi-Fi and if it's connected it kill's comitup hotspot and web interface? I need to add some command there. Is it possible?

Thank you for this project! It really helps me

**Comment by davesteele** [comment]
If you have a single WiFi interface, the hotspot and web service will automatically be killed once connected upstream.

If there is something else you need to do, see _external_callback_ in "man 5 comitup-conf".

**Comment by davesteele** [comment]
Just saw your screen shot. The variable definition is commented out (to show the default). Remove the leading "# ".

**Comment by GrandChriss** [comment]
I mean, maybe there's possibility to check wifi connection and start command if connected?

**Comment by davesteele** [comment]
Yes, look up _external_callback_.

**Comment by davesteele** [comment]
Something like:

    # cat /usr/local/bin/comitup-callback
    #!/bin/bash
    
    if  [[ "$1" == "CONNECTED" ]] ; then
        ...
    fi
    
    # chmod 755 /usr/local/bin/comitup-callback

**Comment by GrandChriss** [comment]
So what I should do? How launch bash script after callback CONNECTED?

**Comment by davesteele** [comment]
I don't have any other guidance here.
