### ISSUE TITLE
turn hotsport off using wifi adapter

### ISSUE THREAD

**Issue by ashah7** [davesteele/comitup#21]
Hi
Very good project, been looking for a while for something like this, not sure why finding this has taken so long.  
I'm using a wifi dongle and wanted to know if its possible to disable the hotsport on wlan0 when a connection has been established?  Rather than leaving it running.  I'm just need a connection on wlan1 (dongle).
Because there is no authentication for connecting to the hotspot I fear this might be a security issue if always left advertised.

thanks

**Comment by davesteele** [comment]
There is no automatic provision for that right now. You would get the desired effect if you removed the dongle. Or, you could probably get this by disabling the comitup service and restarting.

**Comment by krebbi** [comment]
Yeah, I do have the same problem. I need to attach a wifi-dongle as the raspberry is mounted inside a housing thus the internal antennas range is dramatically reduced.

**Comment by davesteele** [comment]
See enable_appliance_mode and set_primary_device in comitup.conf.

I haven't tried this.

**Comment by krebbi** [comment]
That's getting a bit strange now. 
wlan0 has a connection to a network. wlan1 doesn't. 
With "primary_wifi_device: wlan1" Comitup goes to HOTSPOT Mode with wlan1 but a connection fails from the Smartphone.
![Bildschirmfoto 2019-06-17 um 16 09 49](https://user-images.githubusercontent.com/3884521/59613912-075c9600-9120-11e9-940f-449a8c77db59.png)
![IMG_6910](https://user-images.githubusercontent.com/3884521/59613950-16434880-9120-11e9-962c-9a5bf3ae1549.PNG)
![Bildschirmfoto 2019-06-17 um 16 50 44](https://user-images.githubusercontent.com/3884521/59613971-1fccb080-9120-11e9-9e75-947f4f148c30.png)

**Comment by davesteele** [comment]
That suggests either that the software is not respecting the appliance mode/primary device settings correctly, or this may be due to the NetworkManager race bug that lead to the previous long startup delay.

**Comment by davesteele** [comment]
I just tried this. It worked fine for me.

It actually solved a problem. The second (wifi) adapter (an RTL8188CUS) was getting the wlan0 assignment, but did not respond well to being assigned hotspot responsibility. With wlan1 set to the primary device, it now works fine with either appliance mode setting.
