### ISSUE TITLE
Information, installation script.

### ISSUE THREAD

**Issue by qwksilver** [davesteele/comitup#215]
Below is a script I developed, from your instructions, that saves the original files if someone were to want to back out.  This also seems to consistently install the current version without issues.  Feel free to adopt or share this file.  The proper file extension is only .sh but github won't let me share it that way.

[comitup.sh.txt](https://github.com/davesteele/comitup/files/9491534/comitup.sh.txt)
working on 4-7-22 buster(10) or bullseye(11)
working on 9-6-22 buster(10) (note i can find no changes to this os, even the ver# matches the 4-7-22 edition

not working on 9-6-22 bullseye(11)  use `sudo apt-get install comitup`, it needs no extra work so far.

**Comment by davesteele** [comment]
Looks useful. Note that I haven't tested it.

Anyone coming across this should know that there are [disk images](https://davesteele.github.io/comitup/) of Raspios with comitup installed.

**Comment by davesteele** [comment]
I added a link to this page from the [wiki](https://github.com/davesteele/comitup/wiki/Installing-Comitup).

**Comment by m1dnight** [comment]
Not sure if this is the right place to start this discussion, but have you had any chance on getting it wokring @qwksilver ? Is there anything I can do to help to get it working on bullseye?

**Comment by Jeroen6** [comment]
Hey, thanks. It works. 
Do you think there is a way to make the script not kill the ssh-session?

**Comment by mpentler** [comment]
This seems to be missing `systemctl enable NetworkManager.service` which is leading me to reimage yet another time tonight.

**Comment by davesteele** [comment]
@mpentler , and all, you need to be aware that there is a [Comitup image](http://davesteele.github.io/comitup/#getting-comitup), which is just Raspberry Pi OS with Comitup installed.

Once you have your reimage done, try running:

    gpg --keyring /usr/share/keyrings/debian-keyring.gpg --no-default-keyring --list-key "David Steele"

The Comitup images are signed with this key.

**Comment by mpentler** [comment]
I appreciate that - but lots of us are adding this to something we're already building and thiught "ah - I need to add this functionality!" at a later date. We're not starting from scratch, you know?

Otherwise the script was great, I just wanted to flag it up.
