### ISSUE TITLE
RPM Builds

### ISSUE THREAD

**Issue by MrMEEE** [davesteele/comitup#222]
Hi

I have setup a RPM repo with builds of comitup..

https://rpm.awx.wiki/OpenMower/

I don't know if it's usable by anyone else, but now it's there.. 

Anywhere I can add this info?

**Comment by davesteele** [comment]
I added a link to the Wiki [Installation Page](https://github.com/davesteele/comitup/wiki/Installing-Comitup) and to the [Home Page](https://davesteele.github.io/comitup/).

Thanks for the work.
