### ISSUE TITLE
Order of multiple WLAN devices

### ISSUE THREAD

**Issue by krebbi** [davesteele/comitup#23]
In the readme is written

_____
If two wifi interfaces are available, the first will persistently remain the hotspot, and the second will get the external connection. When both are connected, forwarding and masquerading are enabled so that hotspot-connected devices can access external networks.
_____

but here it's exactly the other way around:

wlan0 (build in raspi wifi) connects to choosen network
wlanwlx74da... (USB wifi dongle) seems to be the hotspot

but i cannot see an open hotspot. something is strange here.... 

is there a way to choose the "primary wlan device" in comitup/nm somehow?

**Comment by davesteele** [comment]
Not currently.

The assignment of  "ap_device" and "link_device" is done in [modemgr.py](https://github.com/davesteele/comitup/blob/master/comitup/modemgr.py).

What is the make and model of your usb wifi adapter?

**Comment by krebbi** [comment]
thanks a lot!
