### ISSUE TITLE
Login via ssh fails

### ISSUE THREAD

**Issue by KirPot05** [davesteele/comitup#238]
I tried the default user-name and password provided in docs for the comitup service

Credentials used:
userName: comitup
password: comitup

Device used:
Raspberrypi Zero W

Still the login fails. Are the credentials being changed in the latest versions?

**Comment by davesteele** [comment]
Those credentials are for recent Comitup images. If you installed the package, it doesn't apply.

**Comment by KirPot05** [comment]
Then for the package, what are the credentials to be used?

**Comment by davesteele** [comment]
That login is not managed by comitup. Use whatever your account login is.
