### ISSUE TITLE
Where can I find older OS images?

### ISSUE THREAD

**Issue by gbernal** [davesteele/comitup#243]
Hi @davesteele 

Thank you for sharing such a helpful project. I have been searching for the bullseye version of the OS, and I can't seem to find it. Unfortunately one of the libraries is no longer supported with the latest kernels, so I have to keep using the older version. 

Would you be able to share that version I believe it was [debian/1.38-1](https://github.com/davesteele/comitup/releases/tag/debian%2F1.38-1) release.

Thank you once again,
Guillermo

**Comment by davesteele** [comment]
Sorry, I only save one previous image. That's not going to help you.

Debs for the comitup package itself are [archived](https://davesteele.github.io/comitup/archive.html).
