### ISSUE TITLE
Rename Wifi SSID

### ISSUE THREAD

**Issue by rajavel1990** [davesteele/comitup#247]
I am trying to rename the Wifi SSID from comitup-586 to the Project name that we are building like "ABC Techtronics" how do we get this changed to reflect the project name as the Wifi SSID ?

**Comment by davesteele** [comment]
See the (ap_name)[https://davesteele.github.io/comitup/man/comitup-conf.pdf] configuration parameter.

**Comment by rajavel1990** [comment]
I have tried changing the ap_name but i dont see the changes it is still displaying comitup-586.

<img width="570" alt="Screenshot 2024-06-20 at 6 47 58 PM" src="https://github.com/davesteele/comitup/assets/43663845/69a242ac-c423-40a8-8686-7b9ff41d548d">
<img width="382" alt="Screenshot 2024-06-20 at 6 42 41 PM" src="https://github.com/davesteele/comitup/assets/43663845/97b88e52-3a24-43da-8590-601997b37f52">

**Comment by davesteele** [comment]
The "#" is a comment character. Remove it and the leading space.

**Comment by rajavel1990** [comment]
This Worked. Thanks David.,
