### ISSUE TITLE
Need to Configure Comitup in Existing project

### ISSUE THREAD

**Issue by rajavel1990** [davesteele/comitup#248]
I have followed the instructions on this page: https://github.com/davesteele/comitup/wiki/Installing-Comitup to get comitup configured. 

I have successfully executed the first command sudo apt-get install comitup

When i run the 2nd command sudo systemctl enable NetworkManager.service i am getting a error Failed to enable unit: Unit file NetworkManager.service does not exist.
 how do i get past this to proceed with the next steps ? 

Is there any video tutorial for manual installation on preinstalled raspbian os ?

<img width="544" alt="Screenshot 2024-06-21 at 9 20 06 PM" src="https://github.com/davesteele/comitup/assets/43663845/9d2d1d28-2941-4152-81da-67054af0ab24">

**Comment by davesteele** [comment]
Installing comitup should have pulled in NetworkManager, by way of python-networkmanager. 

Is it installed?

    dpkg --list | grep network-manager

If it is, try rebooting to reset systemd.

**Comment by rajavel1990** [comment]
I just figured out that i am running Buster and there were some additional steps that needs to be done. Is there a comitup image that has buster installed. The one that I download is with the latest bookworm

**Comment by rajavel1990** [comment]
I have followed all the instructions provided in https://github.com/davesteele/comitup/wiki/Installing-Comitup and https://davesteele.github.io/comitup/ppa.html to get the comitup installed without any errors., but after i reboot i dont see any wifi displayed i connected an ethernet cable to ssh into the pi. I logged in through VNC and i see the the wifi is disconnected and it displays 

No wireless interfaces found
connection to dhcpcd lost

What should be done now to fix this ?

**Comment by davesteele** [comment]
Network manager needs to own the WiFi interfaces. That means removing/commenting them in /etc/interfaces.

**Comment by rajavel1990** [comment]
I dont see any file by the name in etc/interfaces but i have deleted the file named interfaces in etc/network/interfaces

<img width="655" alt="Screenshot 2024-06-23 at 9 30 44 AM" src="https://github.com/davesteele/comitup/assets/43663845/54d066e2-5a6f-44ec-8efa-bef6546023d6">
