### ISSUE TITLE
Possible to speed up reboot time?

### ISSUE THREAD

**Issue by BrianGilbert** [davesteele/comitup#249]
commitup is running a process that slows down shutdown, it takes 1.5 minutes.. any way to reduce that timer?

Raspberry Pi 4, Bookworm

**Comment by davesteele** [comment]
Probably. It should shut down instantaneously. I haven't looked into this.

**Comment by davesteele** [comment]
Can't reproduce.

**Comment by BrianGilbert** [comment]
@davesteele apologies, it was reboot time that has the pause..

using `sudo shutdown -r now` I get the following during the shutdown procedure

![IMG_2190](https://github.com/davesteele/comitup/assets/114017/490bcead-cb2f-45e8-ba91-3246d971975c)

**Comment by davesteele** [comment]
Take a look in the comitup (/var/log/comitup.log) and systemd (journalctl -u comitup) logs.

**Comment by davesteele** [comment]
Comitup is having trouble with NetworkManager. Can you try adding "KillSignal=SIGKILL" to the [Service] section of the comitup.service file (and run "systemctl daemon-reload")?
