### ISSUE TITLE
Comitup fails to start if disk is full

### ISSUE THREAD

**Issue by theronic** [davesteele/comitup#25]
Comitup is attempting to write to logs on startup, which prevents it from starting. This is a problem if another process filled the disk, which means you can't get it back online.

**Comment by davesteele** [comment]
NetworkManager logs as well.

Comitup could be configured to not log, or I guess to tolerate log write failures. If you are going for long life, you'll want to avoid logging to the SD card in the first place.

**Comment by krebbi** [comment]
Had the same problem. I disabled logging completely as it destroys the SD-Card on a Raspberry.

**Comment by davesteele** [comment]
Oddly, GitHub recommended [log2ram](https://github.com/azlux/log2ram) to me today
