### ISSUE TITLE
Set hotspot to 5ghz

### ISSUE THREAD

**Issue by Dwull98** [davesteele/comitup#251]
Hi, is it in some way possible to set the hotspot comitup creates to 5ghz?

**Comment by davesteele** [comment]
The Comitup hotspot is a NetworkManager "connection". You can edit the connection after it is created. There is a connection parameter that [controls the wifi band](https://people.freedesktop.org/~lkundrak/nm-docs/nm-settings.html#id-1.2.6.4.31).

**Comment by Dwull98** [comment]
Many thanks!
