### ISSUE TITLE
Apache2 and Comitup

### ISSUE THREAD

**Issue by dubaleeiro** [davesteele/comitup#258]
Hi,

This is more a question than an issue. I have been trying to make a Django application working with Apache2 and Comitup on a Raspberry Pi and looked at some issues like [this one](https://github.com/davesteele/comitup/issues/201).

My approach to make Apache2 and Comitup coexist is to start the Apache server only after Comitup successfully connects to a WiFi network by changing the `start-apache.service` like this:

`
[Unit]
Description=Start Apache after WiFi connection
After=comitup.service
`

This did not work unfortunately. Would someone be so kind and give me some hints? Thanks !

**Comment by davesteele** [comment]
Just because Comitup is running doesn't mean that WiFi is connected. 

See #142 and the [web_service](https://github.com/davesteele/comitup/blob/8ed8f908b1bfe25ee139fb7d35846e7cb60f0afb/conf/comitup.conf#L28) [configuration parameter](https://davesteele.github.io/comitup/man/comitup-conf.pdf).

**Comment by dubaleeiro** [comment]
Changing the `web_service` parameter to `apache2.service` did the trick !

Thanks a lot, @davesteele !
