### ISSUE TITLE
Hotspot security

### ISSUE THREAD

**Issue by augisbud** [davesteele/comitup#28]
Hello, is there anyway for me to add a password to my hotspot?

**Comment by davesteele** [comment]
Not from Comitup (yet), but Network Manager stores the hotspot configuration in /etc/NetworkManager/system (from memory). You can add a password to that file, then restart.

**Comment by davesteele** [comment]
Add this to /etc/NetworkManager/system-connections/comitup-&lt;nn&gt;:

    [wifi-security]
    key-mgmt=wpa-psk
    psk=supersecretpassword

**Comment by augisbud** [comment]
Thanks
