### ISSUE TITLE
apt-get gives an old version.

### ISSUE THREAD

**Issue by augisbud** [davesteele/comitup#29]
Hello, when I use the image provided I get totally different design, than when I use apt-get install comitup. Any possibility to change that?

**Comment by davesteele** [comment]
Design?

If you mean web design, you can do an apt-get upgrade on the booted image to get the most recent version.

**Comment by augisbud** [comment]
I did that, the design hasn't changed, I will try again

**Comment by augisbud** [comment]
UPDATE: did sudo apt-get update && sudo apt-get upgrade, the design hasn't changed.

**Comment by davesteele** [comment]
What comitup versions are we talking about?

**Comment by augisbud** [comment]
the latest i'm getting from sudo apt-get install comitup on raspbian stretch

**Comment by augisbud** [comment]
How can I install directly by using git clone, and the setup.py file?

**Comment by davesteele** [comment]
Ah. You need to add a line to /etc/apt/sources.list referencing the comitup repository to get the latest:

    deb http://davesteele.github.io/comitup/repo comitup main

Or you can get the latest deb from the [archive](https://davesteele.github.io/comitup/archive.html).

**Comment by augisbud** [comment]
still not getting it :(

**Comment by davesteele** [comment]
The command to install via setup.py is "python3 setup.py install". 

N.B. I've never done that.

The git archive currently builds the latest deb, using the "debuild" command.

Re - still not getting it. Make sure you do the "apt-get update" after updating sources.list.

**Comment by augisbud** [comment]
```
pi@raspberry:~ $ sudo apt install ./comitup_1.3.1-1_all.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'comitup' instead of './comitup_1.3.1-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 comitup : Depends: python3-networkmanager (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```
output from the deb installation.

YUP I'm dumb, forgot to sudo apt-get update

**Comment by davesteele** [comment]
Re installing from git. For development, what I do is install the deb, then use a small deploy script that copies py files from the cli, comitup, and web directories to the corresponding directories in /usr/share/comitup/, then restart the comitup service.
