### ISSUE TITLE
IOS Connection Problem

### ISSUE THREAD

**Issue by davesteele** [davesteele/comitup#32]
There is a problem connecting to the Comitup hotspot using IOS devices.

Edit - Disputed. Appears to work on modern devices.

**Comment by augisbud** [comment]
I think they have trouble connecting when there is no internet for eg. when there is no ping to apple.com, so you would need to implement captive portal connectivity, just guessing

**Comment by davesteele** [comment]
Captive portal is implemented in the current master.

The IOS issue is present even if a clear path to the Internet is available.

**Comment by davesteele** [comment]
This does not affect Macs, only iPads, and presumably iPhones.

**Comment by krebbi** [comment]
In 1.5.1 (from the linux repo) it opens the capture portal site form comitup as expected. 
On iOS 12.4

**Comment by davesteele** [comment]
Good to hear. My options are much older.
