### ISSUE TITLE
devicename in hotspot name

### ISSUE THREAD

**Issue by krebbi** [davesteele/comitup#33]
Hi,

do you think it's possible to get the devicename into the hotspot name somehow? 

instead of the "comitup-82" I would like to have "device123-hotspot"

**Comment by davesteele** [comment]
See the "ap_name" parameter in the conf file.

https://davesteele.github.io/comitup/man/comitup-conf.5.html

**Comment by krebbi** [comment]
Yes, already using this. But as we set up several devices per day I would love to see a possibility to have the devicename as internal variable available like <nnnn>. Maybe <hostname> ?

**Comment by davesteele** [comment]
Ah
