### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by iv-med** [davesteele/comitup#37]
After installing comitup (older and newer versions) don't create the AP networks.
Raspberry Pi Zero W.

**Comment by DaleMitchell** [comment]
@davesteele ?

**Comment by davesteele** [comment]
I'll try it this weekend.

**Comment by davesteele** [comment]
What version of Comitup do you have installed?

**Comment by davesteele** [comment]
I tried the 2019-03-30 Comitup image, which is a recent Raspbian which also includes Comitup 1.4-1. Installed on a Pi Zero W with and without an extra Wifi interface. It worked fine.

Note that the hotspot disappears when there is an upstream connection, unless you have the second wifi interface.
