### ISSUE TITLE
PYTHONPATH problem during development (title changed by maintainer)

### ISSUE THREAD

**Issue by DaleMitchell** [davesteele/comitup#39]
I tried running `comitup` from the command line:
```
ImportError: cannot import name persist
```

@davesteele, when was the last time you tried running `setup.py` on a fresh image of Raspbian? It appears that many things are broken due to poor maintenance of the GitHub repo.

**Comment by davesteele** [comment]
I've probably never run setup.py on Raspbian. It serves as a config file for the debian build. Try the deb file.

**Comment by davesteele** [comment]
It occurs to me that you may not have seen the [home page](https://davesteele.github.io/comitup/).

**Comment by DaleMitchell** [comment]
Sorry if I came across as grouchy earlier, didn't get enough sleep.

I have seen the homepage, it sets high expectations for the software that I
like, but I'm frustrated that I'm getting these errors with the Python
files in the master repo! If I had a fix, I wouldn't hesitate to make a
pull request for the benefit of others.

**Comment by davesteele** [comment]
You pretty much have to have a deb install for the environment to work. For development after that, I use a small deploy script to scp the project tree from a remote computer to a local project tree, and then copy the files to the individual subdirectories in /usr/share/comitup/. The last step could be skipped with some work to address the path problem you're seeing. But, I prefer to edit the project on a remote system, which means that some sort of custom deploy process is required for me.

**Comment by DaleMitchell** [comment]
Okay... so the `setup.py` doesn't really do what people expect it to do?
There's more configuration that needs to be done beyond running `setup.py
build` and `setup.py install`? Why don't we have `setup.py` do everything
that needs to be done?

**Comment by DaleMitchell** [comment]
Okay... so the `setup.py` doesn't really do what people expect it to do?

There's more configuration that needs to be done beyond running `setup.py build` and `setup.py install`? 

Why don't we have `setup.py` do everything that needs to be done?

**Comment by davesteele** [comment]
setup.py is intended to be cross platform, and currently does that job. The .deb file is specifically targeted to a particular OS, and can be uninstalled.

It sounds like you need to go find the tool that is right for you.

**Comment by DaleMitchell** [comment]
Then why do I get:
```
ImportError: cannot import name persist
```

After running build and install with setup.py if it currently does the job?

**Comment by davesteele** [comment]
Because there is a PYTHONPATH problem. You are welcome to attack that, if you wish. Or, you can vote with your feet.

**Comment by DaleMitchell** [comment]
Why did you close an issue that isn't fixed? This issue doesn't have to do with a premade image.
