### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by krebbi** [davesteele/comitup#41]
Comitup needs a lot of time to start. Any ideas how I can speed it up? 

![Bildschirmfoto 2019-05-16 um 11 11 01](https://user-images.githubusercontent.com/3884521/57841714-5c2c8a00-77cb-11e9-95d8-b992b240c8d3.png)

**Comment by davesteele** [comment]
[here](https://github.com/davesteele/comitup/blob/ef4df2a96d6d53ced6ec39fa9e39f8aa21faa177/comitup/comitup.py#L98)

It gives time for the (sole) WiFi interface to get an initial list of APs.

**Comment by krebbi** [comment]
can I reduce this to 2 or 3 ?

**Comment by davesteele** [comment]
Sure. Keep an eye on the reported AP list.

**Comment by krebbi** [comment]
Still have a lot of bootup-time thanks to comitiup. 
Do you think it's possible somehow to not block/delay the boot process this long?

**Comment by davesteele** [comment]
Yes, but it is not a priority for me right now.
