### ISSUE TITLE
Hotspot on every reboot

### ISSUE THREAD

**Issue by kunalkanani93** [davesteele/comitup#46]
Hi Dave,

I am using Comitup from verion 1.4 and  updated to 1.5 now but I always encounter an issue that is on every reboot of RPI comitup hotspot shows up. Even when am in same network. 

Also I have to connect multiple times with Comitup to choose SSID and to get my RPI connected with internet.

I would like to know if I have not installed it properly or doing something wrong. Am just running a GUI app on startup with /etc/profile. 

Thanks

**Comment by davesteele** [comment]
Are you using a Pi with built in wifi? Is there a second wifi adapter? Are you using the recent Buster Raspbian release?

**Comment by kunalkanani93** [comment]
Yes am using built-in wifi, and no second wifi adapter is present. I am using previous release and now might go for Buster Raspbian release.

**Comment by davesteele** [comment]
You can try debugging the connection via nmcli:

sudo systemctl stop comitup
nmcli dev disconnect wlan0
nmcli con up <SSID>

... and check in the logs for NetworkManager messages.

Try "iw dev wlan0 scan" to see if your AP is visible.

And don't be in a hurry to move to Buster.

**Comment by kunalkanani93** [comment]
I did fresh installation now and everything seems ok, ill use this method if it happens again.

Right now, 
- after stopping comitup
- nmcli (showing wlan0 connected to my network)

OK will not move to Buster. Thank you

**Comment by kunalkanani93** [comment]
Hi,

How do I fix this error ? It happened suddenly and comitup is not up. I had cloned RPI image when everything was working fine but it also has same problem now.

![comitup_issue1](https://user-images.githubusercontent.com/9631173/61874711-b30aba00-af06-11e9-862f-6cdb325a9904.PNG)
![comitup2](https://user-images.githubusercontent.com/9631173/61874712-b30aba00-af06-11e9-8abb-ebe555f7c895.PNG)
![comitup3](https://user-images.githubusercontent.com/9631173/61874713-b30aba00-af06-11e9-93dc-dc391165741e.PNG)

**Comment by davesteele** [comment]
See #48
