### ISSUE TITLE
DHCP server handing out dhcp offers while in state connected

### ISSUE THREAD

**Issue by reck7** [davesteele/comitup#49]
In playing around getting 1.6-1 running on raspberry pi zero I have found dhcp server continues to hand out 10.41.0.x addresses while device is in connects state.  I have a esp8266 that come out of deep sleep and connect to wifi. It appears that comitup is seeing the discover broadcasts and is sending out offers.  

![image](https://user-images.githubusercontent.com/53310403/61960298-3376fc80-af93-11e9-84b3-f80688259976.png)

This was in 1.5-1 as well.  Honestly I have not rebooted once got 1.6-1 running with the networkmanager 2.1-1. I am remote to where the device is and did not want to lose connectivity.

**Comment by davesteele** [comment]
DHCP sticks around in dual-interface mode, but it shouldn't in the single interface case. I'll take a look at it.

**Comment by davesteele** [comment]
dnsmasq management was moved from NetworkManager to Comitup in version 1.6.

**Comment by reck7** [comment]
I did a purge of comitup, did an apt autoremove and the installed again to pick up your changes from today.  It still seems to be handing out DHCP offers. 
![image](https://user-images.githubusercontent.com/53310403/61972944-ceca9a80-afb0-11e9-8b5d-6414356c31df.png)

**Comment by davesteele** [comment]
Today's changes addressed a different bug. 

The fix for this will look more like a0b2e2b66 (this is untested).
