### ISSUE TITLE
where is wifi station configuration file?

### ISSUE THREAD

**Issue by Blimpyway** [davesteele/comitup#60]
Hi, 
After installing/configuring comitup, 
I need to remove/change wifi station credentials in comitup, however, I cannot find where the ssid/passwd entries are.  the /etc/wpa_supplicant/wpa_supplicant.conf is empty and I could not find them in any comitup config file in /etc/ 

I use it with a different wifi dongle which does not support AP mode, and since it cant enter AP mode the comitup-web interface does not start and I cannot change wifi setting through it. 
And I don't know how to change wifi credentials, for station mode.

**Comment by davesteele** [comment]
Connection configuration information is in /etc/NetworkManager/sysconfig.

If you are running dual interface mode, and the USB interface is coming up as the first interface, you can select the internal interface for AP duty in /etc/comitup.conf.
