### ISSUE TITLE
Doesn't Connect to Wifi

### ISSUE THREAD

**Issue by krebbi** [davesteele/comitup#63]
Somehow my device does't connect to the choosen Wifi via Captive Portal. But using comitup-cli to connect works.

**Comment by davesteele** [comment]
In my case, that happens when I type in the password wrong.

Are there any non-ASCII characters involved?

**Comment by krebbi** [comment]
no. the password contains 5 lowercase characters and 4 digits.

**Comment by davesteele** [comment]
and the AP name?

**Comment by krebbi** [comment]
RTMDD-130058-94

**Comment by davesteele** [comment]
I'm unable to replicate.

**Comment by davesteele** [comment]
There is a fix in v1.9 that can explain this behavior in older versions.
