### ISSUE TITLE
Hide Access point(SSID)

### ISSUE THREAD

**Issue by Muzzamil1** [davesteele/comitup#66]
Hi, @davesteele  Thanks for the Great project!
I just want to ask, is it possible to hide the access point(SSID)?
And how to connect if there is a network that requires a user name or something like a login key?

**Comment by davesteele** [comment]
Yiou can make the AP hidden by adding "hidden=TRUE" to the "[wifi]" section of the NetworkManager configuration file in /etc/NetworkManager/system-connections. (See https://developer.gnome.org/NetworkManager/stable/nm-settings.html)

Login authentication for upstream APs is discussed in #65.

**Comment by Muzzamil1** [comment]
Ok, thanks. I will try.

**Comment by Muzzamil1** [comment]
Hi, @davesteele  I try to hide the network but it didn't work. 
I did the following steps:
`cd /etc/NetworkManager/system-connections`
`sudo nano wifiTest-0000.nmconnection`
and added `hidden=TRUE` in wifi section.

![steps](https://user-images.githubusercontent.com/53085438/67376596-dbee2a00-f59d-11e9-9aec-a0caf80c0e91.PNG)

Then I clear the previously saved configuration using  `comitup-cli` and then reboot the Pi.
But after booting I can **still see the Access Point**. Then I go to `wifiTest-0000.nmconnection` in which I added the `hidden=TRUE` and that **line** was **no** longer there.
Am I missing something or doing something wrong?

**Comment by davesteele** [comment]
Sorry about that. I remembered last night that the Hotspot config is currently remade on every connect. Currently, you would need to add this config item to the [source code](https://github.com/davesteele/comitup/blob/4694554df8e826f7e024f4cfd0172123efed60b3/comitup/nm.py#L262).

**Comment by Muzzamil1** [comment]
I added `'hidden': True,` , then clear the previously saved configuration using `comitup-cli` and then reboot the Pi but I can still see the **AP** on my mobile.

![changes](https://user-images.githubusercontent.com/53085438/67463708-5d57c200-f65b-11e9-87c7-bf6b486c40c0.PNG)

**Comment by davesteele** [comment]
You are charting new territory at this point. Check if the config file matches what you expect.

**Comment by Muzzamil1** [comment]
I checked 
`sudo nano /etc/NetworkManager/system-connections/wifiTest-0000.nmconnection`
But there is **no hidden=True** in that file.

**Comment by davesteele** [comment]
Ok, so check the documentation for NetworkManager AddConnection for the right parameter.
