### ISSUE TITLE
Problems when used with external wifi 

### ISSUE THREAD

**Issue by Anjum9694** [davesteele/comitup#69]
Hi,
Trying to use my Pi along with your hotspot and wifite.
When I plug in my external adapter the ssh connection breaks and a new hotspot is being made on the wlan1.

I did the primary wlan device setting as my internal wifi wlan0 but this still happens.

**Comment by Anjum9694** [comment]
Edit: No problems now I used the comitup lite image :)

**Comment by davesteele** [comment]
I'm glad you found a solution.
