### ISSUE TITLE
Pi zero W not supported ?

### ISSUE THREAD

**Issue by pagaille** [davesteele/comitup#7]
Hi,

As far as I can see the Pi zero W is not supported. The AP just don't show up, even one without SSID.

Is there anything we can do ?

Thanks

**Comment by davesteele** [comment]
I'm using it on a Zero W right now without issue. What version are you using? Did you use the SD card image, or install the package?

**Comment by pagaille** [comment]
Thanks for your answer. I tried both. I checked that /etc/interfaces was empty. How can I help debug the issue ?

**Comment by davesteele** [comment]
Try running 'comitup-cli' as root, and see what that tells you ('[man comitup-cli](https://davesteele.github.io/comitup/man/comitup-cli.1.html)'). Also check the comitup log in /var/log.

If I'm doing a lot of debugging, I kill the service ('sudo systemctl stop comitup' and 'comitup-web') and run it from the command line ('sudo /usr/sbin/comitup').

**Comment by pagaille** [comment]
/var/log showed` comitup - WARNING - Error connecting hotspot`
I'll investigate further but sadly I only can access it through wifi since I don't have a HDMI monitor right now. That complicates things a bit ;-)

**Comment by pagaille** [comment]
Long story short, it works now.

I tried installing from scratch using the latest packages, comitup_1.2.3-1_all.deb and python3-networkmanager_2.0.1-4_all.deb using gdesbi to resolve the dependencies.

I don't know why the image doesn't work. No time to test again right now.

THANKS for that really good and clever software !

**Comment by davesteele** [comment]
That warning indicates an error with NetworkManager, which, I believe, is mitigated with python3-networkmanager 2.0.1-4. That package is included on the comitup repo, and is pulled in by the lastest comitup version.
