### ISSUE TITLE
Comitup can't connect to avahi-daemon after several hours running - avahi-daemon[294]: Too many objects for client ':1.11', client request failed.

### ISSUE THREAD

**Issue by Baltix** [davesteele/comitup#77]
Comitup can't connect to avahi-daemon after several hours running, I see these messages in journal log:
Nov 28 17:00:53 BaltixPi avahi-daemon[294]: Too many objects for client ':1.11', client request failed.
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout
Nov 28 17:00:53 BaltixPi comitup[487]:     connecting_fail()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 186, in connecting_fail
Nov 28 17:00:53 BaltixPi comitup[487]:     set_state('CONNECTING')
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 281, in set_state
Nov 28 17:00:53 BaltixPi comitup[487]:     state_info.start_fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 56, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     returnvalue = fn(*args, **kwargs)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 163, in connecting_start
Nov 28 17:00:53 BaltixPi comitup[487]:     mdns.clear_entries()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 113, in clear_entries
Nov 28 17:00:53 BaltixPi comitup[487]:     establish_group()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/mdns.py", line 50, in establish_group
Nov 28 17:00:53 BaltixPi comitup[487]:     bus.get_object(DBUS_NAME, server.EntryGroupNew()),
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     return self._proxy_method(*args, **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
Nov 28 17:00:53 BaltixPi comitup[487]:     **keywords)
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
Nov 28 17:00:53 BaltixPi comitup[487]:     message, timeout)
Nov 28 17:00:53 BaltixPi comitup[487]: dbus.exceptions.DBusException: org.freedesktop.Avahi.TooManyObjectsError: Too many object
Nov 28 17:00:53 BaltixPi comitup[487]: Traceback (most recent call last):
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 73, in wrapper
Nov 28 17:00:53 BaltixPi comitup[487]:     fn()
Nov 28 17:00:53 BaltixPi comitup[487]:   File "/usr/share/comitup/comitup/states.py", line 193, in connecting_timeout

**Comment by davesteele** [comment]
Is the pi connected upstream during this time?

Do you have connections defined?
