### ISSUE TITLE
[Feature Request] Keep hotspot up if spare wifi interface available

### ISSUE THREAD

**Issue by CallumJHays** [davesteele/comitup#80]
The IP of my Pi changes a lot on campus, particularly because I'm using it for mobile robots. It would be nice to be able to plug in an additional wifi dongle and be able to find the Pi's current local IP via the web interface (& allow re-connection to other networks because why not)

**Comment by davesteele** [comment]
It does this already. It is controlled by [enable_appliance_mode](enable_appliance_mode), and is enabled by default.

**Comment by CallumJHays** [comment]
Thanks I missed that when I read through the conf files
