### ISSUE TITLE
version in default Buster repo doesn't work

### ISSUE THREAD

**Issue by schweini** [davesteele/comitup#82]
simply using apt-get to install the version in Buster's repo (ver 1.3.1-1) results in a nonworking system for me.

Using your ppa does work - may I recommend either pointing this out in the docs, or updating the version in the official repo?

**Comment by davesteele** [comment]
See the [wiki](https://github.com/davesteele/comitup/wiki/Installing-Comitup).

**Comment by schweini** [comment]
Yes, thanks to the wiki, I got it to work. But the main homepage makes it sound as if the official repo version should be good enough.
