### ISSUE TITLE
how to disconnect from network and go back to hotspot mode

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davesteele/comitup#85]
Is there a way to disconnect from a network and go back to hostspot mode.

**Comment by davesteele** [comment]
There is a delete command in comitup-cli, or delete the connection with nmcli.

**Comment by mrsstaceyseigle** [comment]
comitup-cli then d option gives the option to delete the connections also we can delete the connection with nmcli

Problems. When using nmcli it takes comitup a while to detect and go back to hotspot mode. 

could you please give us the option to input options with the command like
sudo comitup-cli d   or sudo comitup-cli -d

Im using the raspberry pi with a push button to delete the connection

**Comment by davesteele** [comment]
Noted.

Try something like "(echo d; echo q) | comitup-cli".

**Comment by mrsstaceyseigle** [comment]
Yes (echo d; echo q) | comitup-cli Works great. 

I love to see a enhancement on your next version to use it like " comitup-cli -option"
