### ISSUE TITLE
DNS name instead of http://10.41.0.1/

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davesteele/comitup#86]
Is there a way that we can use a name like raspberrypi.local instead of http://10.41.0.1/  to get to the page that show all of the wifi network

**Comment by davesteele** [comment]
Yes, such names are being published, and can be customized in the conf file. But, host support for that is spotty. See the wiki.

**Comment by mrsstaceyseigle** [comment]
Editing the conf file: Do we have to edit it before we install it onto the raspberry pi or can we edit after it is installed? if so can you provide us with the path where the files should be located on the raspberry pi
