### ISSUE TITLE
Check connection status

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davesteele/comitup#93]
comitup when connected shows connection status. Is there a command or can you create a command that we can run that will print to terminal connected and the network we connected to only without the other options

**Comment by davesteele** [comment]
You could hack a copy of comitupcli.py to just return [state info](https://github.com/davesteele/comitup/blob/518a36db2bc3a9e15fd8e1664e905c3b9bd85d68/cli/comitupcli.py#L98).

Also, look at the 'nmcli' command (e.g. "nmcli dev show wlan0")

**Comment by mrsstaceyseigle** [comment]
Thank you!
