### ISSUE TITLE
Connecting to config webpage

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davesteele/comitup#96]
Dave thank you for Comitup. 

Lets say that we connect to a network. Once done Comitup will exit out of Hotspot mode. This makes getting back to the webpage where SSID become unreachable. Is there a way we can access this page again to make changes without deleting the current connection which would put comitup back into hotspot mode?

**Comment by davesteele** [comment]
If you have a second Wifi adapter (a usb adapter), The hotspot will remain, and the usb stick will be used to make the upstream connection. But, the web page, which only supports the unconnected state, will not be available. Use ssh in that case.

If you do not have the second adapter, you can find the IP address for ssh access via [ZeroConf](https://github.com/davesteele/comitup/wiki/ZeroconfBrowser).
