### ISSUE TITLE
Config folder missing in v1.10

### ISSUE THREAD

**Issue by mrsstaceyseigle** [davesteele/comitup#97]
How do we change ap names in the new version 1.10.   The config folder is missing

**Comment by davesteele** [comment]
The active comitup.conf should be in /etc.

**Comment by mrsstaceyseigle** [comment]
Okay. Sorry the file structure looked a little different from the github page.

Can you provide us a file patch where we can  change the domain from 10.41.0.1 to something different if we need to

**Comment by davesteele** [comment]
It is actually hard coded in a [number of places](https://github.com/davesteele/comitup/search?q=10.41.0&unscoped_q=10.41.0) in the source. You can change it there, but be careful.
